name: Codebase validation

on:
  workflow_call:
    inputs:
      # PHP
      php_enabled:
        type: boolean
        required: false
        default: false
        description: Run PHP validation
      php_version:
        type: string
        required: false
        default: '8.2'
        description: Which version to use for PHP validation.
      # Docker
      docker_enabled:
        type: boolean
        required: false
        default: false
        description: Run Dockerfile validation (with hadolint)
      docker_threshold:
        type: string
        required: false
        default: 'error'
        description: Failure threshold for hadolint. Defaults to 'error'
      # Shell
      shell_enabled:
        type: boolean
        required: false
        default: false
        description: Run Shellcheck
      shell_threshold:
        type: string
        required: false
        default: 'error'
        description: Failure threshold for Shellcheck
      shell_check_together:
        type: string
        required: false
        default: 'yes'
        description: Check all shell scripts together
      shell_format:
        type: string
        required: false
        default: 'gcc'
        description: Output format for Shellcheck
      # Helm chart
      helm_enabled:
        type: boolean
        required: false
        default: false
        description: Run Helm validation

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

    - name: Code checkout
      uses: actions/checkout@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      if: inputs.docker_enabled == true
      with:
        dockerfile: Dockerfile
        failure-threshold: ${{ inputs.docker_threshold }}

    - name: Check all shell scripts
      uses: ludeeus/action-shellcheck@master
      if: inputs.shell_enabled == true
      with:
        severity: ${{ inputs.shell_threshold }}
        check_together: ${{ inputs.shell_check_together }}
        format: ${{ inputs.shell_format }}

    - name: Check all php files
      uses: firehed/lint-php-action@v1
      if: inputs.php_enabled == true
      with:
        php-version: ${{ inputs.php_version }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      if: inputs.helm_enabled == true
      with:
        version: v3.9.2

    - uses: actions/setup-python@v2
      if: inputs.helm_enabled == true
      with:
        python-version: 3.7

    - name: Set up chart-testing
      if: inputs.helm_enabled == true
      uses: helm/chart-testing-action@v2.2.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      if: inputs.helm_enabled == true
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      if: inputs.helm_enabled == true
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      if: inputs.helm_enabled == true && steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install
      if: inputs.helm_enabled == true
